# E.D.A.

La 2 ieme  phase de  notre  projet  va constituer  à  faire  une analyse exploratoire des données afin  de debusquer des  patterns  qui  nous serviront  prochainement/

In [4]:
# commencons  par  importer  toutes  les  librairies dont  nous aurons  besoins  pour  le  traitement  de  ce dataset
import  pandas as  pd 
import  numpy as  np
import matplotlib.pyplot as  plt
from matplotlib.collections import LineCollection
%matplotlib inline
import seaborn as sns
sns.set_style('darkgrid')
import scipy.stats as st
from scipy.stats import ks_2samp
from sklearn.cluster import KMeans
from scipy.cluster.hierarchy import dendrogram, linkage, fcluster
import statsmodels.formula.api as smf
import statsmodels.api as sm
import math as ma
from collections import Counter

#Une fois  les  modules  importés  nous allons  charger  les données

## Chargement de la table

In [8]:
df = pd.read_csv("df_clean")
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91031 entries, 0 to 91030
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              91031 non-null  int64
 1   name                            91031 non-null  object
 2   host_id                         91031 non-null  int64
 3   host_name                       91031 non-null  object
 4   neighbourhood                   91031 non-null  object
 5   latitude                        91031 non-null  float64
 6   longitude                       91031 non-null  float64
 7   room_type                       91031 non-null  object
 8   price                           91031 non-null  float64
 9   minimum_nights                  91031 non-null  int64
 10  number_of_reviews               91031 non-null  int64
 11  last_review                     91031 non-null  object
 12  reviews_per_month               91031 non-null  float64
 13  calculated_host_listings_count  91031 non-null  int64
 14  availability_365                91031 non-null  int64
 15  number_of_reviews_ltm           91031 non-null  int64
dtypes: float64(4), int64(7), object(5)
memory usage: 11.1+ MB

,id,name,host_id,host_name,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm
0,5396,Your Perfect Paris Studio On Île Saint-Louis,7903,Borzou,Hôtel-de-Ville,48.852470,2.358350,Entire home/apt,88.0,3,425,2024-11-23,2.260000,1,77,51
1,7964,Sunny Apartment With Balcony,22155,Anaïs,Opéra,48.874170,2.342450,Entire home/apt,150.0,7,5,2015-09-14,0.030000,1,0,0
2,9952,Paris Petit Coin Douillet,33534,Elisabeth,Popincourt,48.862380,2.369570,Entire home/apt,150.0,4,52,2024-09-24,0.360000,1,250,3
3,11487,"Heart Of Paris, Brand New Aparment.",42666,Brigitte,Popincourt,48.863510,2.371100,Entire home/apt,80.0,30,13,2024-09-27,0.090000,2,246,5
4,12452,Voltaire Charm,48733,Irene,Popincourt,48.859740,2.379320,Entire home/apt,201.0,1,62,2024-10-11,0.770000,1,34,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91026,1304562779094087796,Studio Ensoleillé Sur Canal,38574929,Anna,Buttes-Chaumont,48.888360,2.382689,Entire home/apt,100.0,30,0,2023-01-01,1.065495,1,85,0
91027,1304667478167694444,Studio Bohémien,595527331,Ahmed,Ménilmontant,48.864770,2.391108,Entire home/apt,80.0,1,0,2023-01-01,1.065495,1,180,0
91028,1305050902233494632,Cozy Apartment - Marais - Pelee,156775524,Merveil,Popincourt,48.859996,2.369208,Entire home/apt,818.0,1,0,2023-01-01,1.065495,107,264,0
91029,1305061192394005038,Cozy Apartment - Tour Eiffel - Finlay,156775524,Merveil,Vaugirard,48.852970,2.288317,Entire home/apt,840.0,1,0,2023-01-01,1.065495,107,316,0
91030,1305099664946300068,Parc Monceau - Beautiful Apartment,539380225,Charles,Batignolles-Monceau,48.892425,2.319849,Entire home/apt,66.0,2,0,2023-01-01,1.065495,25,157,0

## quesques statistiques et autres elements d'explorations

In [10]:
#Voyons quelques  modalités constituant certaines variables categoprielles 
df.room_type.unique()

array(['Entire home/apt', 'Private room', 'Shared room', 'Hotel room'],
      dtype=object)

In [12]:
#Voyons quelques  modalités constituant certaines variables categoprielles 
df.neighbourhood.unique()

array(['Hôtel-de-Ville', 'Opéra', 'Popincourt', 'Buttes-Montmartre',
       'Buttes-Chaumont', 'Louvre', 'Reuilly', 'Élysée', 'Panthéon',
       'Entrepôt', 'Vaugirard', 'Palais-Bourbon', 'Bourse', 'Passy',
       'Temple', 'Ménilmontant', 'Batignolles-Monceau', 'Luxembourg',
       'Observatoire', 'Gobelins'], dtype=object)